# Generated by Django 5.0.1 on 2024-02-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='availableTime',
            new_name='available_Time',
        ),
    ]
